export const APIURL = {
  BaseURL: 'https://admin.cliquesocial.co/api/',
  ImangeURL: 'https://admin.cliquesocial.co/public/storage',
  iconUrl: 'https://admin.cliquesocial.co/',
  ImageUrl: 'https://admin.cliquesocial.co',
  Accept: 'Accept',
  Bearer: 'Bearer ',

  login: 'login',
  loginotp: 'loginotp',
  register: 'register',
  ragisterwithotp: 'ragisterwithotp',
  forgetPassword: 'forget-password',
  otpVerification: 'otp-verification',
  changePassword: 'change-password',
  emailCheck: 'emailcheck',
  nearbyUsers: 'nearbyusers',
  usersDetails: 'usersdetails',
  profileUpdate: 'profileupdate',
  loginProfileUpdate: 'loginprofileupdate',
  companyAdd: 'companyadd',
  addContact: 'addcontact',
  removeContact: 'removecontact',
  addContactList: 'addcontactlist',
  writeCard: 'writecard',
  socialDelete: 'socialdelete',
  countryList: 'countrylist',
  putOrder: 'putorder',
  getTempProfile: 'gettempprofile',
  tempProfileUpdate: 'tempprofileupdate',
  tempActiveInactive: 'tempactiveinactive',
  qrGenerated: 'qrgenerated',

  //

  userLogin: 'login-via-email',
  newRegister: 'new-register',
  socialIcons: 'gettempicone',
  validateCard: 'validatecard',
  userprofileupdate: 'userprofileupdate',
  makePayment: 'makepayment',
};
