export const APIURL = {
  BaseURL: 'https://dev.thewebtual.com/clique/api/',
  ImangeURL: 'https://dev.thewebtual.com/clique/public/storage',

  Accept: 'Accept',
  Bearer: 'Bearer ',

  login: 'login',
  loginotp: 'loginotp',
  register: 'register',
  ragisterwithotp: 'ragisterwithotp',
  forgetPassword: 'forget-password',
  otpVerification: 'otp-verification',
  changePassword: 'change-password',
  emailCheck: 'emailcheck',
  nearbyUsers: 'nearbyusers',
  usersDetails: 'usersdetails',
  profileUpdate: 'profileupdate',
  loginProfileUpdate: 'loginprofileupdate',
  companyAdd: 'companyadd',
  addContact: 'addcontact',
  removeContact: 'removecontact',
  addContactList: 'addcontactlist',
  writeCard: 'writecard',
  socialDelete: 'socialdelete',
  countryList: 'countrylist',
  putOrder: 'putorder',
  getTempProfile: 'gettempprofile',
  tempProfileUpdate: 'tempprofileupdate',
  tempActiveInactive: 'tempactiveinactive',
  qrGenerated: 'qrgenerated',
};
