export const IMG = {
  InitialFlow: {
    Intro1: require('../Assets/Images/InitialFlowIcons/ic_intro1.png'),
    Intro2: require('../Assets/Images/InitialFlowIcons/ic_intro2.png'),
    Intro3: require('../Assets/Images/InitialFlowIcons/ic_intro3.png'),
    Intro4: require('../Assets/Images/InitialFlowIcons/ic_intro4.png'),
    Intro5: require('../Assets/Images/InitialFlowIcons/ic_intro5.png'),
    Clique: require('../Assets/Images/InitialFlowIcons/ic_clique.png'),
    EyeVisible: require('../Assets/Images/InitialFlowIcons/ic_eyeVisible.png'),
    EyeInvisible: require('../Assets/Images/InitialFlowIcons/ic_eyeInvisible.png'),
    Insta: require('../Assets/Images/InitialFlowIcons/ic_insta.png'),
    RedPlay: require('../Assets/Images/InitialFlowIcons/ic_redPlay.png'),
    LinkdId: require('../Assets/Images/InitialFlowIcons/ic_linkdIn.png'),
    MinUserIcon: require('../Assets/Images/InitialFlowIcons/ic_minUser.png'),
    MinEmailIcon: require('../Assets/Images/InitialFlowIcons/ic_minEmail.png'),

    CardLeft: require('../Assets/Images/InitialFlowIcons/card_left.png'),
    CardRight: require('../Assets/Images/InitialFlowIcons/card_right.png'),
    CardCenter: require('../Assets/Images/InitialFlowIcons/card_center.png'),
  },
  OtherFlow: {
    MenuIcon: require('../Assets/Images/OtherImages/ic_menu.png'),
    BackIcon: require('../Assets/Images/OtherImages/ic_back.png'),
    PencilIcon: require('../Assets/Images/OtherImages/ic_pencil.png'),
    ScanIcon: require('../Assets/Images/OtherImages/ic_scan.png'),
    SettingIcon: require('../Assets/Images/OtherImages/ic_setting.png'),
    BusinessIcon: require('../Assets/Images/OtherImages/ic_business.png'),
    SocialIcon: require('../Assets/Images/OtherImages/ic_socialMedias.png'),
    MusicIcon: require('../Assets/Images/OtherImages/ic_music.png'),
    PaymentIcon: require('../Assets/Images/OtherImages/ic_payment.png'),
    ExternalLinkIcon: require('../Assets/Images/OtherImages/ic_externalLink.png'),
    DownArrowIcon: require('../Assets/Images/OtherImages/ic_downArrow.png'),
    EditIcon: require('../Assets/Images/OtherImages/ic_edit.png'),
    SyncIcon: require('../Assets/Images/OtherImages/ic_sync.png'),
    TempImage: require('../Assets/Images/OtherImages/ic_temp.png'),
    TickIcon: require('../Assets/Images/OtherImages/ic_tick.png'),

    Background: require('../Assets/Images/OtherImages/background.png'),
    CallIcon: require('../Assets/Images/OtherImages/ic_call.png'),
    SocialMailIcon: require('../Assets/Images/OtherImages/ic_mailSocial.png'),
    FacebookIcon: require('../Assets/Images/OtherImages/ic_facebook.png'),
    TwitterIcon: require('../Assets/Images/OtherImages/ic_twitter.png'),
    InstaIcon: require('../Assets/Images/OtherImages/ic_insta.png'),
    LinkdInIcon: require('../Assets/Images/OtherImages/ic_linkdin.png'),
    PayIcon: require('../Assets/Images/OtherImages/ic_pay.png'),
    DocsIcon: require('../Assets/Images/OtherImages/ic_doc.png'),
    PrivacyIcon: require('../Assets/Images/OtherImages/ic_privacy.png'),
    RemoveIcon: require('../Assets/Images/OtherImages/ic_remove.png'),
    SpotifyIcon: require('../Assets/Images/OtherImages/ic_spotify.png'),
    WebIcon: require('../Assets/Images/OtherImages/ic_web.png'),
    YoutubeIcon: require('../Assets/Images/OtherImages/ic_youtube.png'),
    RightArrowIcon: require('../Assets/Images/OtherImages/ic_rightArrow.png'),
    LinkIcon: require('../Assets/Images/OtherImages/ic_link.png'),
    QRIcon: require('../Assets/Images/OtherImages/ic_qrCode.png'),
    WorkIcon: require('../Assets/Images/OtherImages/ic_work.png'),
    AddressIcon: require('../Assets/Images/OtherImages/ic_address.png'),
    AddIcon: require('../Assets/Images/OtherImages/ic_add.png'),
    CameraIcon: require('../Assets/Images/OtherImages/ic_camera.png'),
  },
  TabFlow: {
    Home: require('../Assets/Images/TabbarIcons/ic_home.png'),
    HomeSelect: require('../Assets/Images/TabbarIcons/ic_homeSele.png'),
    Profile: require('../Assets/Images/TabbarIcons/ic_profile.png'),
    ProfileSelect: require('../Assets/Images/TabbarIcons/ic_profileSele.png'),
    Pin: require('../Assets/Images/TabbarIcons/ic_pin.png'),
    PinSelect: require('../Assets/Images/TabbarIcons/ic_pinSele.png'),
    Scan: require('../Assets/Images/TabbarIcons/ic_scan.png'),
    ScanSelect: require('../Assets/Images/TabbarIcons/ic_scanSele.png'),
    Message: require('../Assets/Images/TabbarIcons/ic_message.png'),
    MessageSele: require('../Assets/Images/TabbarIcons/ic_messageSele.png'),
    Setting: require('../Assets/Images/TabbarIcons/ic_setting.png'),
    SettingSele: require('../Assets/Images/TabbarIcons/ic_settingSele.png'),
  },
};
